version: '3.8'

services:
  db:
    image: postgres:13
    container_name: books_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nest-app:
    image: ibodullayevhusernamedocker/nest-app
    container_name: nestjs-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:3000'
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_HOST: db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
